"""Update DistributionRule model

Revision ID: 120de9b6edee
Revises: d6c9a76ab188
Create Date: 2025-03-17 18:17:17.461589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120de9b6edee'
down_revision: Union[str, None] = 'd6c9a76ab188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_rules', sa.Column('payment_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution_rules', 'payment_days')
    # ### end Alembic commands ###
