"""Добавлено поле рогрузка разгрузка

Revision ID: 16aac168f55a
Revises: 6c7dd9cf3d24
Create Date: 2025-03-19 10:58:58.600111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16aac168f55a'
down_revision: Union[str, None] = '6c7dd9cf3d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('unloading_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('loading_adress', sa.String(), nullable=True))
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'loading_adress')
    op.drop_column('orders', 'unloading_address')
    # ### end Alembic commands ###
