"""Update requests table

Revision ID: 22605bcf87b9
Revises: d7f262aef5cc
Create Date: 2025-03-10 23:28:24.234649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22605bcf87b9'
down_revision: Union[str, None] = 'd7f262aef5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
