"""Remove owner_id from requests

Revision ID: 3415e80b18ee
Revises: 575a531d50eb
Create Date: 2025-03-13 21:51:12.332524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3415e80b18ee'
down_revision: Union[str, None] = '575a531d50eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_owner_id_fkey', 'requests', type_='foreignkey')
    op.drop_column('requests', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('requests_owner_id_fkey', 'requests', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
