"""Добавлено поле cargo_id в orders

Revision ID: 4a6c12ebac59
Revises: dd96e189230c
Create Date: 2025-03-18 09:21:42.970464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6c12ebac59'
down_revision: Union[str, None] = 'dd96e189230c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cargo_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cargo_id')
    # ### end Alembic commands ###
