"""Изменение is_published с Boolean на String

Revision ID: 6c7dd9cf3d24
Revises: e03ebfdb015a
Create Date: 2025-03-18 19:16:26.138267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7dd9cf3d24'
down_revision: Union[str, None] = 'e03ebfdb015a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'is_published',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'is_published',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
