"""Create Platform

Revision ID: 7959894cb5f5
Revises: e735a6bdd17d
Create Date: 2025-03-20 10:31:21.351278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7959894cb5f5'
down_revision: Union[str, None] = 'e735a6bdd17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_rules', sa.Column('platform', sa.String(), nullable=False, server_default="Transport2"))
    op.add_column('distribution_rules', sa.Column('auto_publish_auction', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_distribution_rules_platform'), 'distribution_rules', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_rules_platform'), table_name='distribution_rules')
    op.drop_column('distribution_rules', 'auto_publish_auction')
    op.drop_column('distribution_rules', 'platform')
    # ### end Alembic commands ###
