"""Update DistributionRule model

Revision ID: 79683f61f979
Revises: 514717289e63
Create Date: 2025-03-16 16:40:43.914442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79683f61f979'
down_revision: Union[str, None] = '514717289e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_rules', sa.Column('loading_city', sa.String(), nullable=True))
    op.add_column('distribution_rules', sa.Column('unloading_city', sa.String(), nullable=True))
    op.add_column('distribution_rules', sa.Column('logistician', sa.String(), nullable=True))
    op.create_index(op.f('ix_distribution_rules_loading_city'), 'distribution_rules', ['loading_city'], unique=False)
    op.create_index(op.f('ix_distribution_rules_unloading_city'), 'distribution_rules', ['unloading_city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_rules_unloading_city'), table_name='distribution_rules')
    op.drop_index(op.f('ix_distribution_rules_loading_city'), table_name='distribution_rules')
    op.drop_column('distribution_rules', 'logistician')
    op.drop_column('distribution_rules', 'unloading_city')
    op.drop_column('distribution_rules', 'loading_city')
    # ### end Alembic commands ###
