"""Add bid_price to requests

Revision ID: a234839257bb
Revises: 3415e80b18ee
Create Date: 2025-03-13 23:13:53.713574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a234839257bb'
down_revision: Union[str, None] = '3415e80b18ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('weight_volume', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('loading_types', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('order_type', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('bid_price', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('cargo_name', sa.String(), nullable=True))
    op.alter_column('requests', 'logistician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('requests_logistician_id_fkey', 'requests', type_='foreignkey')
    op.drop_column('requests', 'is_auction')
    op.drop_column('requests', 'volume')
    op.drop_column('requests', 'weight')
    op.drop_column('requests', 'rate_factory')
    op.drop_column('requests', 'rate_auction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('rate_auction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('rate_factory', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('is_auction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('requests_logistician_id_fkey', 'requests', 'logists', ['logistician_id'], ['id'])
    op.alter_column('requests', 'logistician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('requests', 'cargo_name')
    op.drop_column('requests', 'comment')
    op.drop_column('requests', 'bid_price')
    op.drop_column('requests', 'order_type')
    op.drop_column('requests', 'loading_types')
    op.drop_column('requests', 'vehicle_type')
    op.drop_column('requests', 'weight_volume')
    # ### end Alembic commands ###
