"""Update requests table

Revision ID: d7f262aef5cc
Revises: 980dbf053988
Create Date: 2025-03-10 23:03:10.158983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f262aef5cc'
down_revision: Union[str, None] = '980dbf053988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('platform', sa.String(), nullable=False, server_default='default_platform'))
    op.add_column('requests', sa.Column('load_date', sa.Date(), nullable=False, server_default='2000-01-01'))
    op.add_column('requests', sa.Column('unload_date', sa.Date(), nullable=False, server_default='2000-01-01'))
    op.add_column('requests', sa.Column('rate_factory', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('rate_auction', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('cargo_type', sa.String(), nullable=False, server_default='default_cargo'))
    op.add_column('requests', sa.Column('weight_volume', sa.String(), nullable=False, server_default='default_weight_volume'))
    op.add_column('requests', sa.Column('vehicle_type', sa.String(), nullable=False, server_default='default_vehicle'))
    op.add_column('requests', sa.Column('load_unload_type', sa.String(), nullable=False, server_default='default_load_unload'))
    op.add_column('requests', sa.Column('logistician', sa.String(), nullable=False, server_default='default_logistician'))
    op.add_column('requests', sa.Column('ati_price', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('requests', 'status')
    op.drop_column('requests', 'description')
    op.drop_column('requests', 'title')
    op.drop_column('requests', 'price')
    # ### end Alembic commands ###

    # Удаляем значения по умолчанию после обновления существующих записей
    op.alter_column('requests', 'platform', server_default=None)
    op.alter_column('requests', 'load_date', server_default=None)
    op.alter_column('requests', 'unload_date', server_default=None)
    op.alter_column('requests', 'cargo_type', server_default=None)
    op.alter_column('requests', 'weight_volume', server_default=None)
    op.alter_column('requests', 'vehicle_type', server_default=None)
    op.alter_column('requests', 'load_unload_type', server_default=None)
    op.alter_column('requests', 'logistician', server_default=None)
    op.alter_column('requests', 'is_published', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('requests', 'is_published')
    op.drop_column('requests', 'ati_price')
    op.drop_column('requests', 'logistician')
    op.drop_column('requests', 'load_unload_type')
    op.drop_column('requests', 'vehicle_type')
    op.drop_column('requests', 'weight_volume')
    op.drop_column('requests', 'cargo_type')
    op.drop_column('requests', 'rate_auction')
    op.drop_column('requests', 'rate_factory')
    op.drop_column('requests', 'unload_date')
    op.drop_column('requests', 'load_date')
    op.drop_column('requests', 'platform')
    # ### end Alembic commands ###
