"""Добавлены loading_address и unloading_address

Revision ID: e735a6bdd17d
Revises: 16aac168f55a
Create Date: 2025-03-19 11:10:37.534978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e735a6bdd17d'
down_revision: Union[str, None] = '16aac168f55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('loading_address', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'loading_adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('loading_adress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'loading_address')
    # ### end Alembic commands ###
