"""Updated Request model

Revision ID: f1af4435ee90
Revises: 6d2a38d4873d
Create Date: 2025-03-13 21:48:00.689376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1af4435ee90'
down_revision: Union[str, None] = '6d2a38d4873d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('requests', 'logistician_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'requests', 'users', ['owner_id'], ['id'])
    op.drop_column('requests', 'vehicle_type')
    op.drop_column('requests', 'cargo_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('cargo_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.alter_column('requests', 'logistician_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('requests', 'owner_id')
    # ### end Alembic commands ###
