"""Update DistributionRule model

Revision ID: f5608be4d9c0
Revises: 79683f61f979
Create Date: 2025-03-16 16:49:09.175290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5608be4d9c0'
down_revision: Union[str, None] = '79683f61f979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_distribution_rules_id'), 'distribution_rules', ['id'], unique=False)
    op.drop_column('distribution_rules', 'loading_city_id')
    op.drop_column('distribution_rules', 'logist_id')
    op.drop_column('distribution_rules', 'unloading_city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_rules', sa.Column('unloading_city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('distribution_rules', sa.Column('logist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('distribution_rules', sa.Column('loading_city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_distribution_rules_id'), table_name='distribution_rules')
    # ### end Alembic commands ###
